export const pokemonTypes = [
    "normal",
    "fire",
    "water",
    "electric",
    "grass",
    "ice",
    "fighting",
    "poison",
    "ground",
    "flying",
    "psychic",
    "bug",
    "rock",
    "ghost",
    "dragon",
    "dark",
    "steel",
    "fairy",
  ]
  
  export const typeColors: Record<string, string> = {
    normal: "neutral",
    fire: "red",
    water: "blue",
    electric: "yellow",
    grass: "green",
    ice: "cyan",
    fighting: "orange",
    poison: "purple",
    ground: "amber",
    flying: "sky",
    psychic: "pink",
    bug: "lime",
    rock: "stone",
    ghost: "violet",
    dragon: "indigo",
    dark: "zinc",
    steel: "slate",
    fairy: "rose",
  }
  